#!/bin/bash

# GCLOUD ENV VARS
export GCLOUD_PROJECT_ID="terraform-gcp-lab"
export GCLOUD_JSON_KEY_PATH="${CIRCLE_WORKING_DIRECTORY}/cloud/credentials/credential.json"
export GOOGLE_APPLICATION_CREDENTIALS=${GCLOUD_JSON_KEY_PATH}
export GCLOUD_PROJECT_BUCKET_NAME=""
export GCLOUD_PROJECT_REGION=""
