version: 2.1
defaults: &defaults
  working_directory: /root/app
  docker:
    - image: google/cloud-sdk
activate-sa: &activate-sa
  - run:
      name: "Activate SA to the Project"
      command: |
        for v in "$(cat .circleci/cicd-definitions.sh | grep -v ^#)"; do echo "${v}" >> ${BASH_ENV}; done
        source ${BASH_ENV}
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
        gcloud config set project ${GCLOUD_PROJECT_ID}

revoke-sa: &revoke-sa
  - run:
      name: "Revoke SA"
      command: |
        for v in "$(cat .circleci/cicd-definitions.sh | grep -v ^#)"; do echo "${v}" >> ${BASH_ENV}; done
        echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
        echo "${GCLOUD_JSON_KEY_PATH}" grep "client_email" | awk '{print $2}' | grep -o '".*"' | sed 's/"//g'
        gcloud auth revoke devops-sa@terraform-gcp-lab.iam.gserviceaccount.com

only-releasable: &only-releasable
  filters:
    branches:
      only:
        - develop
        - master
non-releasable: &non-releasable
  filters:
    branches:
      ignore:
        - develop
        - master

jobs:
  Prepare Credentials:
    <<: *defaults
    steps:
      - checkout
      - <<: *activate-sa

  GCP GKE Node Pool Creation:
    working_directory: /root/app
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP GKE Node Pool Creation"
          command: |
            #echo ${DODRONES_GCP_MY_LABS_SA} > ${TF_VAR_key}
            cd cloud/terraform
            terraform init -backend-config="bucket=${TF_VAR_gcp_bucket}" -backend-config="prefix=terraform"
  
  GCP Bucket Update:
    <<: *defaults
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP Bucket Update"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil acl ch -u AllUsers:R gs://${GCLOUD_PROJECT_BUCKET_NAME}/index.html
  
  GCP Publish Site:
    <<: *defaults
    steps:
      - checkout
      - <<: *activate-sa
      - run:
          name: "GCP Publish Site"
          command: |
            source .circleci/cicd-definitions.sh
            gsutil web set -m index.html gs://${GCLOUD_PROJECT_BUCKET_NAME}

  GCP Revoke Credentials:
    <<: *defaults
    steps:
      - checkout
      - <<: *revoke-sa

workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      - Prepare Credentials
      - GCP GKE Node Pool Creation:
          requires:
            - Prepare Credentials
      #- GCP Sync:
          #<<: *only-releasable
          #requires:
            #- Prepare Credentials
      #- GCP Bucket Update:
          #<<: *only-releasable
          #requires:
            #- GCP Sync
      #- GCP Publish Site:
          #<<: *only-releasable
          #requires:
            #- GCP Bucket Update