version: 2.1

defaults: &defaults
  working_directory: /root/app
gcp-image: &gcp-image
  docker:
    - image: google/cloud-sdk
tf-image: &tf-image
  docker:
    - image: hashicorp/terraform:full

only-testing: &only-testing
    filters:
      branches:
        ignore:
          - develop
          - master
          - bugfix
          - patch
          - release
only-releasable: &only-releasable
    filters:
      branches:
        only:
          - develop
          - master
non-releasable: &non-releasable
    filters:
      branches:
        ignore:
          - develop
          - master

jobs:
  App Build Docker Image:
    <<: *defaults
    <<: *gcp-image
    steps:
      - checkout
      - setup_remote_docker
          #docker_layer_caching: true
      - run:
          name: "Build and Push"
          command: |
            if [[ "$(git log --format=oneline -n 1 ${CIRCLE_SHA1} | grep -E "\[tf-destroy\]")" ]]; then
              echo ""
              echo "=================================================================================="
              echo "[$(date +%H:%M:%S)] - Build Docker Image skipped!... [next: Destroying GCP Resources]"
              echo "=================================================================================="
            elif [[ "$(git log --format=oneline -n 1 ${CIRCLE_SHA1} | grep -E "\[tf-apply\]")" ]]; then
              for v in "$(cat .circleci/cicd-definitions.sh | grep -v ^#)"; do echo "${v}" >> ${BASH_ENV}; done
              source ${BASH_ENV}
              echo ${DODRONES_GCP_MY_LABS_SA} > ${GCLOUD_JSON_KEY_PATH}
              gcloud auth activate-service-account --key-file=${GCLOUD_JSON_KEY_PATH}
              gcloud config set project --quiet ${GCLOUD_PROJECT_ID}
            
              gcloud auth --quiet configure-docker

              docker build -t "us.gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:stable" .
              docker push "us.gcr.io/${GCLOUD_PROJECT_ID}/${CIRCLE_PROJECT_REPONAME}:stable"
            else
              echo ""
              echo "=================================================================================="
              echo "[$(date +%H:%M:%S)] - Build Docker Image skipped!... [Nothing to do]"
              echo "=================================================================================="
            fi

  GCP GKE Provisioning:
    <<: *defaults
    <<: *tf-image
    steps:
      - checkout
      - run:
          name: "GCP GKE Node Pool Creation"
          command: "./.circleci/cicd-executor.sh"

  GCP Deploy App:
    <<: *defaults
    <<: *gcp-image
    steps:
      - checkout
      - run:
          name: "GCP Deploy App"
          command: "./.circleci/cicd-executor.sh"

  Testing bash dolibs:
    <<: *defaults
    <<: *tf-image
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Load GCP lib for testing"
          command: "./.circleci/cicd-executor.sh"

workflows:
  version: 2.1
  
  gcloud_workflow:
    jobs:
      # - App Build Docker Image:
      #     <<: *only-releasable
      - GCP GKE Provisioning:
          <<: *only-testing
      #     #requires:
      #     #  - App Build Docker Image
      - GCP Deploy App:
          <<: *only-testing
          requires:
            - GCP GKE Provisioning
      #- Testing bash dolibs:
      #    <<: *only-testing