apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-site-deployment
  #namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key: deployment-dev
    spec:
      containers:
        - name: web-site-deployment-container
          image: us.gcr.io/${GCLOUD_PROJECT_ID}/web-site${K8S_DEPLOYMENT_TAG}
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      #imagePullSecrets:
      #  - name: gcr-secret # Use secret for private container repository in gcr.io

      
        