apiVersion: v1
kind: Service
metadata:
  labels:
    label-key: deployment
  name: ${APP_NAME}-service
spec:
  type: ClusterIP
  ports:
  - name: service-port
    port: 80
    protocol: TCP
  selector:
    label-key: deployment