apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${APP_NAME}-deployment
  #namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        label-key: deployment
    spec:
      containers:
        - name: ${APP_NAME}-deployment-container
          image: ${GCLOUD_CONTAINER_IMAGE}
          imagePullPolicy: Always
          ports:
          - containerPort: 80
      #imagePullSecrets:
      #  - name: gcr-secret # Use secret for private container repository in gcr.io

      
        