apiVersion: v1
kind: Service
metadata:
  labels:
    service-label-key: service-dev
  name: web-site-service
spec:
  type: ClusterIP
  ports:
  - name: service-port
    port: 80
    protocol: TCP
  selector:
    deployment-label-key: deployment-dev